name: Sync lazy to scf(同步文件)
on:
  workflow_dispatch:
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3.0.0
        with:
          source_repo: "https://${{ secrets.PAT2 }}@github.com/jinboyigu/lazy_script.git"
          source_branch: "master"
          destination_repo: "https://${{ secrets.PAT2 }}@github.com/wheatwee/scf.git"
          destination_branch: "main"
      
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.PAT }}
          SKIP_PR: true  
